#!/bin/bash

fail() {
  echo "$@" 1>&2
  exit 1
}

if ! [[ ":$PATH:" == *":$(pwd):"* ]]; then
  PATH="$PATH:$(pwd)"
fi

if ! command -v payload-dumper-go 2>&1 >/dev/null
then
  fail "ERROR: payload-dumper-go is not installed."
fi

while true; do
  case $1 in
    -h)
      # TODO:
      echo "help"
      ;;

    -u|--url)
      if [ "$2" ]; then
        url=$2
        shift
      else
        fail 'ERROR: "--url" requires a non-empty url.'
      fi
      ;;

    -s|--sum|--checksum)
      if [ "$2" ]; then
        known_sha=$2
        shift
      else
        fail 'ERROR: "--checksum" requires a non-empty checksum.'
      fi
      ;;

    --vendor)
      if [ "$2" ]; then
        vendor=$2
        vendor_path="${vendor}/"
        shift
      else
        fail 'ERROR: "--vendor" requires a non-empty vendor.'
      fi
      ;;

    --device)
      if [ "$2" ]; then
        device=$2
        device_path="${device}/"
        shift
      else
        fail 'ERROR: "--device" requires a non-empty device.'
      fi
      ;;

    --filename)
      if [ "$2" ]; then
        filename=$2
        shift
      else
        fail 'ERROR: "--filename" requires a non-empty filename.'
      fi
      ;;

    --full)
      full=true
      ;;

    *)
      break
      ;;
  esac
  shift
done

if [[ $url ]]; then
  filename=$(basename "$url")
  if [[ -d "policies/${vendor_path}${device_path}${filename%.*}" ]]; then
    echo "Directory already exists, exiting..."
    exit
  fi

  wget -q --show-progress $url
  echo "Downloaded '$filename'."
  if [[ $known_sha ]]; then
    echo -n "Verifying checksum SHA-256 against provided..."
    sha=$(sha256sum "$filename" | awk '{ print $1 }')
    if [[ "$known_sha" == "$sha" ]]; then
      echo '  Match.'
    else
      fail '  ERROR: checksum does not match.'
    fi
  fi

  # Assume the unzipped payload is payload.bin
  echo "Unzipping downloaded file..."
  unzip $filename payload.bin
  rm $filename
fi

# We only need system.img and vendor.img
#TODO: we might need odm too (based on vendor)
if ! payload-dumper-go -l payload.bin | grep system | grep -q vendor; then
  fail "ERROR: payload does not contain required partitions."
fi

if [[ $full ]]; then
  echo "Extracting required partitions: product.img, system.img, system_ext.img and vendor.img."
  payload-dumper-go -o extracted -partitions product,system,system_ext,vendor payload.bin
else
  echo "Extracting required partitions: system.img and vendor.img."
  payload-dumper-go -o extracted -partitions system,vendor payload.bin
fi
rm payload.bin


if ! [[ $filename ]]; then
  filename=default
fi

# Mount the required file system 
echo "Mounting filesystems."
mkdir -p mnt/product mnt/system mnt/system_ext mnt/vendor
if [[ $full ]]; then
  sudo mount -o ro extracted/product.img mnt/product
  sudo mount -o ro extracted/system_ext.img mnt/system_ext
fi
sudo mount -o ro extracted/system.img mnt/system
sudo mount -o ro extracted/vendor.img mnt/vendor

# Copy the needed files
echo "Extracting files."
user=`whoami`
policies_dir="policies/${vendor_path}${device_path}${filename%.*}"
mkdir -p $policies_dir
sudo cp mnt/system/system/build.prop $policies_dir
sudo chown $user:$user "${policies_dir}/build.prop"
cp mnt/system/system/etc/selinux/plat_file_contexts $policies_dir
cp mnt/vendor/etc/selinux/vendor_file_contexts $policies_dir
cp mnt/vendor/etc/selinux/precompiled_sepolicy $policies_dir
if [[ $full ]]; then
  mkdir "${policies_dir}/product" "${policies_dir}/system" \
        "${policies_dir}/system_ext" "${policies_dir}/vendor"
  cp -r mnt/product/etc/selinux/* -t "${policies_dir}/product"
  cp -r mnt/system/system/etc/selinux/* -t "${policies_dir}/system"
  cp -r mnt/system_ext/etc/selinux/* -t "${policies_dir}/system_ext"
  cp -r mnt/vendor/etc/selinux/* -t "${policies_dir}/vendor"
fi

# Cleanup
echo "Cleaning up."
if [[ $full ]]; then
  sudo umount -l mnt/product
  sudo umount -l mnt/system_ext
fi
sudo umount -l mnt/system
sudo umount -l mnt/vendor
rmdir mnt/product mnt/system mnt/system_ext mnt/vendor mnt
if [[ $full ]]; then
  rm extracted/system_ext.img
  rm extracted/product.img
fi
rm extracted/system.img
rm extracted/vendor.img